export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_ERRORS = "SET_ERRORS";
export const FETCH_DEVICES = "FETCH_DEVICES";
export const DEVICE_LOADING = "DEVICE_LOADING";
export const TRANSFARE_OWNER = "TRANSFARE_OWNER";
